accounts/urls.py
from .views import register, login, logout, activate, dashboard, forgotPassword, change_password
from .views import resetpassword_validate, resetPassword, my_orders, edit_profile, order_detail
from django.urls import path

app_name='accounts'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', dashboard, name='dashboard'),
    path('forgotPassword/', forgotPassword, name='forgotPassword'),
    path('resetPassword/', resetPassword, name='resetPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', resetpassword_validate, name='resetpassword_validate'),
    
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('my_orders/', my_orders, name='my_orders'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('change_password/', change_password, name='change_password'),
    path('order_detail/<int:order_id>/', order_detail, name='order_detail'),
] 

blucart/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('securelogin/', admin.site.urls),
    path('', home, name='home'),

    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    # Orders:
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from .views import cart, add_cart, remove_cart, remove_cart_item, checkout

app_name = "carts"
urlpatterns = [
    
    path('cart/', cart, name="cart"),
    path('checkout/', checkout, name="checkout"),
    path('add_cart/<int:product_id>/', add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item, name="remove_cart_item"),

] 

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password, phone_number=None):
        if not email:
            raise ValueError('User must have an email address.')
        
        if not username:
            raise ValueError('User must have a username.')
        
        user = self.model(
            # it configures the format of an email, if the email is in capital letters, then changed to lowercase letters
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
            phone_number = phone_number,
        )

        user.set_password(password)

        # saves the user to the DataBase
        user.save(using=self._db)
        return user
    
    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            # it configures the format of an email, if the email is in capital letters, then changed to lowercase letters
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
            password = password,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True

        # saves the user to the DataBase
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    username      = models.CharField(max_length=50, unique=True)
    first_name    = models.CharField(max_length=50)
    last_name     = models.CharField(max_length=50)
    email         = models.EmailField(max_length=100, unique=True)
    phone_number  = models.CharField(max_length=50, blank=True, null=True)

    date_joined   = models.DateTimeField(auto_now_add=True)
    last_login    = models.DateTimeField(auto_now_add=True)

    # required
    is_admin      = models.BooleanField(default=False)
    is_staff      = models.BooleanField(default=False)
    is_active     = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','first_name','last_name']

    objects = MyAccountManager()

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_superuser
    
    def has_module_perms(self, add_label):
        return True
    

class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address_line = models.CharField(blank=True, max_length=120)
    profile_picture = models.ImageField(default="/userProfile/default_profile_pic.png", upload_to='userProfile/')

    def __str__(self):
        return self.user.username
    
    def full_address(self):
        return self.address_line
    

accounts/forms.py
from django import forms
from .models import Account, UserProfile

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter password',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm password',
    }))

    class Meta:
        model = Account
        fields = ['username', 'first_name', 'last_name', 'phone_number', 'email', 'password']

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Password does not match!")

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'Username here'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter first name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter last name'
        self.fields['phone_number'].widget.attrs['placeholder'] = '+ 123 456 789'
        self.fields['email'].widget.attrs['placeholder'] = 'example@gmail.com'

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('username', 'first_name', 'last_name', 'email', 'phone_number')
    
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    
class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages = {'invalid': ("Image files only")}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ('profile_picture', 'address_line')
        help_texts = {
            'username': None,
        }

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from orders.models import Order, OrderProduct
from .forms import RegistrationForm, UserProfileForm, UserForm
from .models import Account, UserProfile
from django.contrib import messages
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from carts.views import _cart_id 
from carts.models import Cart, CartItem
import requests

# VERIFICATION EMAIL
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

# Create your views here.

# REGISTER
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']

            user = Account.objects.create_user(username=username, first_name=first_name, last_name=last_name, email=email, password=password)
            user.phone_number = phone_number
            user.save()

            # Create User Profile
            profile = UserProfile()
            profile.user_id = user.id
            profile.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            mail_subject = 'Please Activate Your Account!'
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            return redirect('/accounts/login/?command=verification&email=' + email)
    
    else:
        form = RegistrationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)


#LOGIN
def login(request):

    if 'next' in request.GET:
        messages.warning(request, 'Please log in to complete checkout.')

    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()

                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)

                    # Get the product variations by cart id
                    product_variation = []
                    for item in cart_item:
                        variation = item.variations.all()
                        product_variation.append(list(variation))

                    # Get the car items for the user to access his product variations
                    cart_items = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_items:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_itemm = CartItem.objects.filter(cart=cart)
                            for item in cart_itemm:
                                item.user = user
                                item.save()

            except:
                pass

            auth.login(request, user)
            messages.success(request, 'You have successfully logged in!')
            url = request.META.get('HTTP_REFERER')
            return redirect('home')
            try:
                query = requests.utils.urlparse(url).query
                # next=/cart/checkout/
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(f"accounts:{nextPage}")
            except:
                return redirect('accounts:dashboard')
        else:
            messages.warning(request, 'Your Email or Password is Wrong. Please Try Again!')
            return redirect('accounts:login')
        
    return render(request, 'accounts/login.html')


# LOGOUT
@login_required(login_url = 'accounts:login')
def logout(request):
    auth.logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("home")


# ACTIVATE ACCOUNT
def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
    
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Congrats! Your account is now activated!")
        return redirect('accounts:login')
    else:
        messages.warning(request, 'Invalid activation link')
        return redirect('accounts:register')


# DASHBOARD
@login_required(login_url = 'accounts:login')
def dashboard(request):
    orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id, is_ordered=True)
    orders_count = orders.count()

    userprofile = UserProfile.objects.get(user_id=request.user.id)
    context = {
        'orders_count': orders_count,
        'userprofile': userprofile,
    }
    return render(request, 'accounts/dashboard.html', context)


def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            # RESET EMAIL PASSWORD
            current_site = get_current_site(request)
            mail_subject = 'Reset Your Password'
            message = render_to_string('accounts/reset_email_password.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, 'Password reset email has been sent to your email address. Please check it out.')
            return redirect('accounts:login')
        else:
            messages.warning(request, 'Account does not exist!')
            return redirect('accounts:forgotPassword')

    return render(request, 'accounts/forgotPassword.html')


def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, "Please reset your password!")
        return redirect('accounts:resetPassword')
    else:
        messages.warning(request, 'This link has expired!')
        return redirect('accounts:login')
    

def resetPassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()

            messages.success(request, 'Password Reset Successful!')
            return redirect('accounts:login')
        else:
            messages.danger(request, "Passwords do not match!")
            return redirect('resetPassword')
    else:
        return render(request, 'accounts/resetPassword.html')
    

@login_required(login_url='accounts:login')
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    context = {
        'orders': orders
    }
    return render(request, 'accounts/my_orders.html', context)


@login_required(login_url='accounts:login')
def edit_profile(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            messages.success(request, 'Your profile has been updated!')
            return redirect('accounts:edit_profile')
    else:
        user_form = UserForm(instance=request.user)

templates/accounts/account_verification_email.html
{% autoescape off %}

Hi {{ user.username }},

Please click on below link to confirm your registration.
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

if It is not you, Please ignore this email.

{% endautoescape %}

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}

<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <h3> <strong class="d-inline-block mr-3">Change Password:</strong> </h3>
            </header>

            <div class="card-body">

                <form method="POST" action="{% url 'accounts:change_password' %}">
                    {% csrf_token %}
                    <label for="current-password">Current Password:</label>
                    <input class="form-control col-md-6" type="password" name="current_password" placeholder="Enter your current password" required>
                    <br>
                    
                    <label for="new-password">New Password:</label>
                    <input class="form-control col-md-6"  type="password" name="new_password" placeholder="new password" required>
                    <br>
                
                    <label for="confirm-password">Confirm New Password:</label>
                    <input class="form-control col-md-6"  type="password" name="confirm_password" placeholder="confirm password" required>
                    <br>
                
                    <button type="submit" class="btn btn-info">Update Password</button>
                  </form>
                                
            </div> 
            </article> 
        </main>
    </div>
    
    
    </section>

{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Logged in as:</strong>
                <span>{{ user.username }}</span>
            </header>
            <div class="card-body">
                <div class="row"> 

                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Total Orders:</h5>
                                <h4>{{ orders_count }}</h4>
                                <a href="{% url 'accounts:my_orders' %}">View Orders</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body bg-dark text-light text-center">
                                <img src="{{userprofile.profile_picture.url}}" class="my-3" alt="User Profile Picture" width="110" style="border-radius:54%">
                                <p> <i class="fa fa-envelope" aria-hidden="true"></i> {{ user.email }}</p>
                                <p><i class="fa fa-phone-square" aria-hidden="true"></i> {{ user.phone_number }}</p>
                            </div>
                        </div>
                    </div>

                    
                </div> 
            </div> 
            </article> 
        </main>
    </div>
    
    
    </section>

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block content %}

<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Update Profile:</strong>
            </header>

            <div class="card-body">

                <div class="text-right">
                    <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture" width="120" style="border-radius: 50px;">
                </div>

                <div class="row"> 
                    <div class="col-md-12">

                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="form-row mb-3">
                                <div class="form-group col-md-6">
                                    <label for="username">Username:</label>
                                    {{ user_form.username }}
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="email">Email:</label>
                                    {{ user_form.email }}
                                </div>
                            </div>

                            <div class="form-row mb-3">
                                <div class="form-group col-md-6">
                                    <label for="first_name">First Name:</label>
                                    {{ user_form.first_name }}
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="last_name">Last Name:</label>
                                    {{ user_form.last_name }}
                                </div>
                            </div>

                            <div class="form-row mb-3">
                                <div class="form-group col-md-6">
                                    <label for="phone_number">Phone Number:</label>
                                    {{ user_form.phone_number }}
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="address_line">Address:</label>
                                    {{ profile_form.address_line }}
                                </div>
                            </div>

                            <div class="form-row mb-3">
                                <div class="form-group col-md-6">
                                    <label for="profile_picture">Profile Picture:</label>
                                    {{ profile_form.profile_picture }}
                                </div>
                            </div>
                            <div class="form-row mb-3">
                                <div class="form-group col-md-6 mt-3">
                                    <button type="submit" class="btn btn-primary">Update Profile</button>
                                </div>
                            </div>
                        </form>
                        
                    
                    </div>
                </div> 
            </div> 
            </article> 
        </main>
    </div>
    
    
    </section>

{% endblock %}

templates/accounts/forgotPassword.html
{% extends 'base.html' %}

{% block content %}

    <section class="section-content padding-y" style="min-height:80vh; background-color: #D8D8D8 ;">

            <div class="card mx-auto" style="max-width: 500px; margin-top:80px; background-color:;">
                <div class="card-body">

                    <h3 class="card-title my-3 text-center">Forgot Password?</h3>

                    <form action="{% url 'accounts:forgotPassword' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="email" class="form-control py-2" placeholder="Enter your email address" name="email">
                        </div>
                    
                        <div class="form-group">
                            <a href="{% url 'accounts:login' %}" class="float-right h5">Got password? Login</a> 
                        
                        </div> 

                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-primary btn-block"> Submit </button>
                        </div>    
                    </form>

                </div> 
            </div> 
        
            <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
            <br><br>
    </section>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <section class="section-content padding-y" style="min-height:84vh;">

        {% if request.GET.command == 'verification' %}

            <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
                <h4> We have sent you a verification email at  <strong style="color: darkorange;"> {{ request.GET.email }}</strong>. <br>
                     Please check your email for the activation link.</h4>
                <br>
                Already verifid? <a href="{% url 'accounts:login' %}">Login</a>
            </div>

        {% else %}

            <div class="card mx-auto" style="max-width: 380px; margin-top:50px;">
                <div class="card-body">

                    <h4 class="card-title mb-4">Sign in</h4>

                    <form action="{% url 'accounts:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email Address" name="email">
                        </div>

                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Password" name="password">
                        </div> 
                        
                        <div class="form-group">
                            <a href="{% url 'accounts:forgotPassword' %}" class="float-right">Forgot password?</a> 
                        
                        </div> 

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Login  </button>
                        </div>    
                    </form>

                </div> 
            </div> 
        
            <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
            <br><br>
         {% endif %}
    </section>
{% endblock %}

templates/accounts/my_orders.html
{% extends 'base.html' %}

{% block content %}

<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
        {% include 'includes/dashboard_sidebar.html' %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Order History:</strong>
            </header>

            <div class="card-body">
                <div class="row"> 
                    <div class="col-md-12">
                        <table class="table table-hover">
                            <thead>

                              <tr>
                                <th scope="col">Order #</th>
                                <th scope="col">Billing Name</th>
                                <th scope="col">Phone </th>
                                <th scope="col">Order Total</th>
                                <th scope="col">Date</th>
                              </tr>

                            </thead>
                            <tbody>
                                {% for order in orders %}
                                    <tr>
                                        <th scope="row"><a href="{% url 'accounts:order_detail' order.order_number %}"> {{ order.order_number }} </a></th>
                                        <td>{{ order.full_name }}</td>
                                        <td>{{ order.phone }}</td>
                                        <td>${{ order.order_total }}</td>
                                        <td>{{ order.created_at }}</td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                          </table>
                    </div>
                </div> 
            </div> 
            </article> 
        </main>
    </div>
    
    
    </section>

{% endblock %}

templates/accounts/resetPassword.html
{% extends 'base.html' %}

{% block content %}

    <section class="section-content padding-y" style="min-height:80vh;">
            <div class="card mx-auto" style="max-width: 440px; margin-top:100px;">
            <div class="card-body">

                <h3 class="card-title my-3">Reset Password</h3>

                <form action="{% url 'accounts:resetPassword' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="Create Password" name="password">
                    </div>

                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="Confirm Password" name="confirm_password">
                    </div> 

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Reset  </button>
                    </div>    
                </form>

            </div> 
            </div> 
        
            <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
            <br><br>
        
    </section>
{% endblock %}

templates/accounts/reset_email_password.html
{% autoescape off %}

Hi {{ user.username }},

As requested, please click below link to reset your password.
http://{{domain}}{% url 'accounts:resetpassword_validate' uidb64=uid token=token %}

If it's not you, Please Ignore this email.

{% endautoescape %}