accounts/urls.py
from .views import register, login, logout, activate, dashboard, forgotPassword, change_password
from .views import resetpassword_validate, resetPassword, my_orders, edit_profile, order_detail
from django.urls import path

app_name='accounts'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', dashboard, name='dashboard'),
    path('forgotPassword/', forgotPassword, name='forgotPassword'),
    path('resetPassword/', resetPassword, name='resetPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', resetpassword_validate, name='resetpassword_validate'),
    
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('my_orders/', my_orders, name='my_orders'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('change_password/', change_password, name='change_password'),
    path('order_detail/<int:order_id>/', order_detail, name='order_detail'),
] 

blucart/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('securelogin/', admin.site.urls),
    path('', home, name='home'),

    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    # Orders:
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from .views import cart, add_cart, remove_cart, remove_cart_item, checkout

app_name = "carts"
urlpatterns = [
    
    path('cart/', cart, name="cart"),
    path('checkout/', checkout, name="checkout"),
    path('add_cart/<int:product_id>/', add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item, name="remove_cart_item"),

] 

store/urls.py
from django.urls import path
from .views import store, product_detail, search, submit_review

app_name = "store"
urlpatterns = [
    path('', store, name='store'),
    path('category/<slug:category_slug>/', store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', product_detail, name='product_detail'),
    path('search/', search, name='search'),
    path('submit_review/<int:product_id>/', submit_review, name='submit_review'),
] 

templates/includes/alerts.html
{% if messages %}
    <div class="messages my-3"></div>
        {% for message in messages %}
            
            <div class="alert alert-{{ message.tags }} text-center text-dark h5" role="alert" id="message">
                {{ message }}
            </div>
            
        {% endfor %}
    </div>
    </ul>
{% endif %}

templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item {% if '/accounts/' == request.path %} active {% endif %}" href="{% url 'accounts:dashboard' %}"> DashBoard </a>
        <a class="list-group-item {% if '/my_orders/' in request.path %} active {% endif %}" href="{% url 'accounts:my_orders' %}"> My Orders </a>
        <a class="list-group-item {% if '/edit_profile/' in request.path %} active {% endif %}" href="{% url 'accounts:edit_profile' %}"> Update Profile</a>
        <a class="list-group-item" href="{% url 'accounts:change_password' %}">Change Password </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
</aside>

templates/includes/footer.html
{% load static %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2023 BlueCart </p>
			</div>
			<div class="col-md-8 text-md-center btn btn-light">
				<span  class="px-2">info@bluecart.io</span>
				<span  class="px-2">+123-456-789</span>
				<span  class="px-2">Inha-ro, Incheon, South Korea</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<script>
	$(document).ready(function(){
		$('.thumb a').click(function(e){
		e.preventDefault();
		$('.mainImage img').attr('src', $(this).attr('href'));
	})
	})
</script>


<!-- ========================= FOOTER END // ========================= -->

templates/includes/header.html
{% load static %}

<header class="section-header">
    <section class="header-main border-bottom">
        <div class="container">
    <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
            <a href="{% url 'home' %}" class="brand-wrap">
                <h2>Blue<i class="fas fa-shopping-cart"></i>Cart
                </h2>
                <!-- <img class="logo" src="{% static 'images/logo.png' %}"> -->
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
            <div class="category-wrap dropdown d-inline-block float-right">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
                    <i class="fa fa-bars"></i> All category 
                </button>

                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'store:store' %}">All products</a>
                    {% for category in links %}
                        <a class="dropdown-item" href="{{ category.get_url }}">{{ category.category_name }}</a> 
                    {% endfor %}
                </div>

            </div>  <!-- category-wrap.// -->
        </div> 
        <a href="{% url 'store:store' %}" class="btn btn-outline-primary">Store</a>
        <!-- SEARCH -->
        <div class="col-lg  col-md-6 col-sm-12 col">
            <form action="{% url 'store:search' %}" class="search" method="GET">
                {% csrf_token %}

                <div class="input-group w-100">
                    <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">
                    
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i>
                      </button>
                    </div>
                </div>

            </form> 
        </div>
        <!-- SEARCH END -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        {% if user.id is None %}
                            <div class="widget-header">
                                <small class="title text-muted">Welcome!</small>
                                <div> 
                                    <a href="{% url 'accounts:login' %}">Log in</a> <span class="dark-transp"> | </span>
                                    <a href="{% url 'accounts:register' %}"> Register</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="widget-header">
                                <small class="title text-muted">Welcome {{ user.username }}!</small>
                                <div> 
                                    <a href="{% url 'accounts:dashboard' %}">Dashboard</a> <span class="dark-transp"> | </span>
                                    <a href="{% url 'accounts:logout' %}">Logout</a>
                                </div>
                            </div>
                        {% endif %}
                        <a href="{% url 'carts:cart' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{ cart_count }}</span>
                        </a>
                    </div> 
                </div> 
    </div>
        </div>
    </section>
    </header>