accounts/urls.py
from .views import register, login, logout, activate, dashboard, forgotPassword, change_password
from .views import resetpassword_validate, resetPassword, my_orders, edit_profile, order_detail
from django.urls import path

app_name='accounts'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('', dashboard, name='dashboard'),
    path('forgotPassword/', forgotPassword, name='forgotPassword'),
    path('resetPassword/', resetPassword, name='resetPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', resetpassword_validate, name='resetpassword_validate'),
    
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('my_orders/', my_orders, name='my_orders'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('change_password/', change_password, name='change_password'),
    path('order_detail/<int:order_id>/', order_detail, name='order_detail'),
] 

blucart/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('securelogin/', admin.site.urls),
    path('', home, name='home'),

    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    # Orders:
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from .views import cart, add_cart, remove_cart, remove_cart_item, checkout

app_name = "carts"
urlpatterns = [
    
    path('cart/', cart, name="cart"),
    path('checkout/', checkout, name="checkout"),
    path('add_cart/<int:product_id>/', add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item, name="remove_cart_item"),

] 

orders/urls.py
from django.urls import path
from .views import place_order, payments, order_complete

app_name = "orders"

urlpatterns = [
    path('place_order/', place_order, name="place_order"),
    path('payments/', payments, name='payments'),
    path('order_complete/', order_complete, name='order_complete'),
    
] 

store/urls.py
from django.urls import path
from .views import store, product_detail, search, submit_review

app_name = "store"
urlpatterns = [
    path('', store, name='store'),
    path('category/<slug:category_slug>/', store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', product_detail, name='product_detail'),
    path('search/', search, name='search'),
    path('submit_review/<int:product_id>/', submit_review, name='submit_review'),
] 

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id
    
class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['review', 'rating']

carts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from store.models import Product, Variation
from .models import Cart, CartItem
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def _cart_id(request):
    """return the cart from the user's session key"""
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

# Create your views here.
def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        total_after_tax = 0

        if request.user.is_authenticated:
                cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (0.5 * total) //100
        total_after_tax = total - tax
    except:
        pass
    context = {
        "total": total,
        "quantity": quantity,
        "cart_items": cart_items,
        "tax": tax,
        "total_after_tax": total_after_tax,
    }

    return render(request, 'store/cart.html', context)



def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)

    # if user is authenticated
    if current_user.is_authenticated:
        product_variation = []


        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()

        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)

            exis_var_list = []
            id =  []
            for item in cart_item:
                existing_variation = item.variations.all()
                exis_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in exis_var_list:
                # increase the cart item quantity
                index = exis_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity = 1,
                user = current_user,
            )

            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        
        return redirect('carts:cart')

    # if user is authenticated
    else:
        product_variation = []


        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()

        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            # existing variations -> database
            # current variation -> product_variation
            # item id - database

            exis_var_list = []
            id =  []
            for item in cart_item:
                existing_variation = item.variations.all()
                exis_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in exis_var_list:
                # increase the cart item quantity
                index = exis_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity = 1,
                cart = cart
            )

            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        
        return redirect('carts:cart')


def remove_cart(request, product_id, cart_item_id):
    
    product = get_object_or_404(Product, id=product_id)

    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)

        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    
    return redirect("carts:cart")

def remove_cart_item(request, product_id, cart_item_id):
    
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    
    return redirect('carts:cart')


@login_required(login_url='accounts:login')
def checkout(request, total=0, quantity=0, cart_items=None):

    if not request.user.is_authenticated:
        return redirect(f'{reverse("accounts:login")}?next={reverse("carts:checkout")}')
    try:
        tax = 0
        total_after_tax = 0
        
        if request.user.is_authenticated:
                cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (0.4 * total) //100
        total_after_tax = total - tax
    except:
        pass

    context = {
        "total": total,
        "quantity": quantity,
        "cart_items": cart_items,
        "tax": tax,
        "total_after_tax": total_after_tax,
    }
    
    return render(request, 'store/checkout.html', context)

store/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from orders.models import OrderProduct

from store.forms import ReviewForm
from .models import Product, ReviewRating, ProductGallery
from category.models import Category
from carts.models import CartItem, Cart
from carts.views import _cart_id
from django.db.models import Q
from django.contrib import messages

# Paginator
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# Create your views here.
def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        # Paginator
        paginator = Paginator(products, 3)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)

        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 9)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)

        product_count = products.count()
    
    categories = Category.objects.all()
    context = {
        'products' : paged_products,
        'categories': categories,
        'product_count': product_count
    }
    return render(request, "store/store.html", context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    except Exception as error:
        raise error
    
    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    # Get the reviews
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)

    # Get the product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)



    context = {
        "single_product": single_product,
        "in_cart": in_cart,
        "orderproduct": orderproduct,
        "reviews": reviews,
        'product_gallery': product_gallery,
    }
    return render(request, 'store/product_detail.html', context)


def search(request):
    product_count = 0
    products = []
    if 'keyword' in request.GET:
        keyword =request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()
    context = {
        "products": products,
        "product_count": product_count,
        "keyword": keyword,
    }    

    return render(request, 'store/store.html', context)


def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id

                data.save()

                messages.success(request, 'Thank for your review!')
                return redirect(url)

templates/store/cart.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <section class="section-content padding-y bg">
        <div class="container">
            {% if not cart_items %}
                <h2 style="text-align: center;">Your Shopping Cart is Empty</h2>
                <a href="{% url 'store:store' %}">
                    <img style="width:40%; margin-left: 30%;" src="https://i.pinimg.com/originals/66/22/ab/6622ab37c6db6ac166dfec760a2f2939.gif" alt="Shopping Cart IMG">
                </a>
                
            {% else %}
            <div class="row">
                <aside class="col-lg-9">
            <div class="card">
            <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">

                <tr class="small text-uppercase">
                    <th scope="col">Product</th>
                    <th scope="col" width="120">Quantity</th>
                    <th scope="col" width="120">Price</th>
                    <th scope="col" class="text-right" width="200"> </th>
                </tr>

            </thead>
                <tbody>

                    {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <figure class="itemside align-items-center">
                                    <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
                                    <figcaption class="info">
                                        <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                                        <p class="text-muted small">
                                            {% if cart_item.variations.all %}
                                                {% for item in cart_item.variations.all %}
                                                    {{ item.variation_category | capfirst }} : {{ item.variation_value  | capfirst }}
                                                    <br>
                                                {% endfor %}
                                            {% endif %} 
                                        </p>
                                    </figcaption>
                                </figure>
                            </td>
                            <td> 
                                <div class="col"> 
                                    <div class="input-group input-spinner">

                                        <div class="input-group-prepend">
                                        <a href="{% url 'carts:remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-minus"></i> </a>
                                        </div>

                                        <input type="text" class="form-control"  value="{{ cart_item.quantity }}">

                                        <div class="input-group-append">

                                            <form action="{% url 'carts:add_cart' cart_item.product.id %}" method="POST">
                                                {% csrf_token %}
                                                {% for item in cart_item.variations.all %}
                                                    <input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst }}">
                                                {% endfor %}
                                                <button class="btn btn-light" type="submit" id="button-plus"> <i class="fa fa-plus"></i> </button>
                                            </form>

                                        </div>
                                    </div> 
                                </div> 
                            </td>
                            <td> 
                                <div class="price-wrap"> 
                                    <var class="price">${{ cart_item.sub_total }}</var> 
                                    <small class="text-muted">${{ cart_item.product.price }} each </small> 
                                </div>

                            </td>
                            <td class="text-right"> 
                            <a href="{% url 'carts:remove_cart_item' cart_item.product.id cart_item.id %}" onclick="return confirm('Are you sure you want to remove this from your cart?')" class="btn btn-outline-danger"> Remove</a>
                            </td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
            </div> 
            
                </aside> 
                <aside class="col-lg-3">
            
                    <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                        <dt>Total price:</dt>
                        <dd class="text-right">${{ total }}</dd>
                        </dl>
                        <dl class="dlist-align">
                        <dt>Tax:</dt>
                        <dd class="text-right">${{ tax }}</dd>
                        </dl>
                        <dl class="dlist-align">
                        <dt>Total:</dt>
                        <dd class="text-right text-dark b"><strong>${{ total_after_tax }}</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="{% static 'images/misc/payments.png' %}" height="27">
                        </p>
                        <a href="{% url 'carts:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                        <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                    </div>
                    </div> 
            
                </aside> 
            
            </div> 
            {% endif %}
        
        </div> 
    </section>
{% endblock %}

templates/store/checkout.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <section class="section-content padding-y bg">
        <div class="container">
            <form action="{% url 'orders:place_order' %}" method="POST">
                {% csrf_token %}

                <div class="row">
                    <aside class="col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title mb-4">Billing Address</h4>
                                
                                    <div class="form-row">

                                        <div class="col form-group">
                                            <label for="">First Name</label>
                                            <input type="text" name="first_name" class="form-control" value="{{ user.first_name }}" required>
                                        </div>

                                        <div class="col form-group">
                                            <label for="">Last Name</label>
                                            <input type="text" name="last_name" class="form-control" value="{{ user.last_name }}" required>
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="col form-group">
                                            <label for="">Email</label>
                                            <input type="email" name="email" class="form-control" value="{{ user.email }}" required>
                                        </div>

                                        <div class="col form-group">
                                            <label for="">Phone Number</label>
                                            <input type="text" name="phone" class="form-control" value="{{ user.phone_number }}" required>
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <div class="col form-group">
                                            <label for="">Address</label>
                                            <input type="text" name="address_line" class="form-control" required>
                                        </div>
                                    </div>

                                    <div class="form-row">
                                        <label for="">Order Note</label>
                                        <textarea name="order_note" rows="2" class="form-control"></textarea>
                                    </div>

                            </div>
                        </div>
                    </aside>

                    <aside class="col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                <table class="table table-borderless table-shopping-cart">
                                    <thead class="text-muted">
                                        <tr class="small text-uppercase">
                                            <th scope="col">Product</th>
                                            <th scope="col" width="120">Quantity</th>
                                            <th scope="col" width="120">Price</th>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        {% for cart_item in cart_items %}
                                            <tr>
                                                <td>
                                                    <figure class="itemside align-items-center">
                                                        <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
                                                        <figcaption class="info">
                                                            <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                                                            <p class="text-muted small">
                                                                {% if cart_item.variations.all %}
                                                                    {% for item in cart_item.variations.all %}
                                                                        {{ item.variation_category | capfirst }} : {{ item.variation_value  | capfirst }}
                                                                        <br>
                                                                    {% endfor %}
                                                                {% endif %} 
                                                            </p>
                                                        </figcaption>
                                                    </figure>
                                                </td>

                                                <td> 
                                                    <label for="">{{ cart_item.quantity }}</label>
                                                </td>

                                                <td> 
                                                    <div class="price-wrap"> 
                                                        <var class="price">${{ cart_item.sub_total }}</var> 
                                                        <small class="text-muted">${{ cart_item.product.price }} each </small> 
                                                    </div> <!-- price-wrap .// -->
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <button type="submit" class="btn btn-light btn-block">Place Order </button>
                            
                                <a href="{% url 'store:store' %}" class="btn btn-success btn-block">Continue Shopping</a>
                                
                            </div>
                        </div>
                    </aside>
                
                </div>

            </form>
        
        </div> 
    </section>

{% endblock %}