blucart/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('securelogin/', admin.site.urls),
    path('', home, name='home'),

    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    # Orders:
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from .views import cart, add_cart, remove_cart, remove_cart_item, checkout

app_name = "carts"
urlpatterns = [
    
    path('cart/', cart, name="cart"),
    path('checkout/', checkout, name="checkout"),
    path('add_cart/<int:product_id>/', add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item, name="remove_cart_item"),

] 

orders/urls.py
from django.urls import path
from .views import place_order, payments, order_complete

app_name = "orders"

urlpatterns = [
    path('place_order/', place_order, name="place_order"),
    path('payments/', payments, name='payments'),
    path('order_complete/', order_complete, name='order_complete'),
    
] 

store/urls.py
from django.urls import path
from .views import store, product_detail, search, submit_review

app_name = "store"
urlpatterns = [
    path('', store, name='store'),
    path('category/<slug:category_slug>/', store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', product_detail, name='product_detail'),
    path('search/', search, name='search'),
    path('submit_review/<int:product_id>/', submit_review, name='submit_review'),
] 

orders/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, Variation

# Create your models here.
class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)

    # Total amount paid:
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled')
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line = models.CharField(max_length=50)
    order_note = models.CharField(max_length=50, blank=True)

    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(max_length=20, blank=True)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    
    def __str__(self):
        return self.first_name
    


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name 

orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'email', 'address_line', 'order_note']

orders/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.core.mail import EmailMessage
from django.template.loader import render_to_string


from store.models import Product
from .models import Order, OrderProduct, Payment
from carts.models import CartItem
from .forms import OrderForm

import datetime
import json

# Create your views here.

def payments(request):
    body = json.loads(request.body)
    order = Order.objects.get(user=request.user, is_ordered=False, order_number=body['orderID'])

    # Store transaction details inside Payment model
    payment = Payment(
         user = request.user,
         payment_id = body['transID'],
         payment_method = body['payment_method'],
         amount_paid = order.order_total,
         status = body['status'],
    )
    payment.save()

    order.payment = payment
    order.is_ordered = True
    order.save()
    
    # Move the cart items to Order Product table
    cart_items = CartItem.objects.filter(user=request.user)

    for item in cart_items:
        order_product = OrderProduct()
        order_product.order_id = order.id 
        order_product.paymnet = payment
        order_product.user_id = request.user.id
        order_product.product_id = item.product_id
        order_product.quantity = item.quantity
        order_product.product_price = item.product.price 
        order_product.ordered = True
        order_product.save()

        cart_item = CartItem.objects.get(id=item.id)
        product_variation = cart_item.variations.all()
        order_product = OrderProduct.objects.get(id=order_product.id)
        order_product.variations.set(product_variation)
        order_product.save()


        # Reduce the quantity of the sold products
        product = Product.objects.get(id=item.product_id)
        product.stock -= item.quantity
        product.save()


    # Clear cart
    CartItem.objects.filter(user=request.user).delete()

    # Send order received email to customer
    mail_subject = 'Thank you for your order!'
    message = render_to_string('orders/order_received_email.html', {
         'user': request.user,
         'order': order,
    })
    to_email = request.user.email
    send_email = EmailMessage(mail_subject, message, to=[to_email])
    send_email.send()

    # Send order number and transaction id back to sendData via Json response
    data = {
         'order_number': order.order_number,
         'transID': payment.payment_id,
    }

    return JsonResponse(data)


def place_order(request, total=0, quantity=0):
    current_user = request.user

    # If count of the products in the cart is less than or equal to 0, then redirect back to shop
    cart_items = CartItem.objects.filter(user=current_user)
    cart_count = cart_items.count()
    if cart_count <=0:
        return redirect('store:store')
    
    tax = 0
    # total_after_tax = 0
    total_with_tax = 0
    for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

    tax = (0.5 * total) //100
    # total_after_tax = total - tax
    total_with_tax = total + tax
    
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            # Store all the billing info inside Order table
            data = Order()

            data.user = current_user
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.phone = form.cleaned_data['phone']
            data.email = form.cleaned_data['email']
            data.address_line = form.cleaned_data['address_line']
            data.order_note = form.cleaned_data['order_note']
            data.ip = request.META.get('REMOTE_ADDR')

            data.order_total = total_with_tax
            data.tax = tax
            data.save()

            # Generate order number
            year = int(datetime.date.today().strftime('%Y'))
            day = int(datetime.date.today().strftime('%d'))
            month = int(datetime.date.today().strftime('%m'))
            date = datetime.date(year, month, day)
            current_date = date.strftime("%Y%m%d")

            # Order number
            order_number = current_date + str(data.id)
            data.order_number = order_number
            data.save()
            
            order = Order.objects.get(user=current_user, is_ordered=False, order_number=order_number)
            context = {
                'order': order,
                'cart_items': cart_items,
                'total': total,
                'tax': tax,
                'total_with_tax': total_with_tax,
            }
            
            return render(request, 'orders/payments.html', context)
        
    return redirect('carts:checkout')


def order_complete(request):
    order_number = request.GET.get('order_number')
    transID = request.GET.get('payment_id')

    try:
        order = Order.objects.get(order_number=order_number, is_ordered=True)
        ordered_products = OrderProduct.objects.filter(order_id=order.id)

        subtotal = 0
        for i in ordered_products:
            subtotal += i.prduct_price * i.quantity

        payment = Payment.objects.get(payment_id=transID)

        context = {
            'order': order,
            'ordered_products' : ordered_products,
            'transID': payment.payment_id,
            'payment': payment,
            'subtotal': subtotal,
        }
        return render(request, 'orders/order_complete.html', context)
    except (Payment.DoesNotExist, Order.DoesNotExist):
        return redirect('home')

templates/orders/order_complete.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<div class="container" style="margin-top: 50px;">
    <center>
        <i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i>
    </center>

    <h2 class="text-center">Payment Successful</h2>
	<br>
	<div class="text-center">
		<a href="{% url 'store:store' %}" class="btn btn-success">Shop more</a>
	</div>
</div>

<div class="container" style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
    <div class="row invoice row-printable">
        <div class="col-md-12">
            <!-- col-lg-12 start here -->
            <div class="panel panel-default plain" id="dash_0">
                <!-- Start .panel -->
                <div class="panel-body p30">
                    <div class="row">
                        <!-- Start .row -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-logo"><img src="{% static 'images/logo.png' %}" alt="Invoice logo" style="max-height: 40px;"></div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-from">
                                <ul class="list-unstyled text-right">
                                    <li><strong>Invoiced To</strong></li>
                                    <li>{{ order.full_name }}</li>
                                    <li>{{ order.address_line }}</li>
                                </ul>
                            </div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <div class="invoice-details mt25">
                                <div class="well">
                                    <ul class="list-unstyled mb0">
                                        <li><strong>Order:</strong> #{{ order.order_number }}</li>
                                        <li><strong>Transaction ID:</strong> #{{ transID }}</li>
                                        <li><strong>Order Date:</strong> {{ order.created_at }}</li>
                                        <li><strong>Status:</strong> {{ payment.status }}</li>
                                    </ul>
                                </div>
                            </div>
                           
                            <div class="invoice-items">
                                <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="per70 text-center">Products</th>
                                                <th class="per5 text-center">Qty</th>
                                                <th class="per25 text-center">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in  ordered_products %}
                                                <tr>
                                                    <td>{{ item.product.product_name }}
                                                        <p class="text-muted small">
                                                            {% if item.variations.all %}
                                                                {% for i in item.variations.all %}
                                                                    {{ i.variation_category | capfirst }} : {{ i.variation_value  | capfirst }}
                                                                    <br>
                                                                {% endfor %}
                                                            {% endif %} 
                                                        </p>
                                                    </td>
                                                    <td class="text-center">{{ item.quantity }}</td>
                                                    <td class="text-center">${{ item.product_price }}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th colspan="2" class="text-right">Sub Total:</th>
                                                <th class="text-center">${{ subtotal }}</th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" class="text-right">Tax:</th>
                                                <th class="text-center">${{ order.tax }}</th>
                                            </tr>
                                            
                                            <tr>
                                                <th colspan="2" class="text-right">Grand Total:</th>
                                                <th class="text-center">${{ order.order_total }}</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div class="invoice-footer mt25">
                                <p class="text-center">Thank you for shopping with us!</p>
                            </div>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                    <!-- End .row -->
                </div>
            </div>
            <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
    </div>
    </div>

{% endblock content %}

templates/orders/order_received_email.html
{% autoescape off %}

Hi {{ user.username }},

Your Order Has Been Received!

Order Number: {{order.order_number}}.

if It is not you, Please ignore this email.

{% endautoescape %}

templates/orders/payments.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <section class="section-content padding-y bg">
        <div class="container">

        <div class="row">

            <aside class="col-lg-8">
                <div class="card">
                    <h5 class="card-header">Billing Address</h5>
                    <div class="card-body">
                        <p class="card-text">{{ order.full_name }}</p>
                        <p class="card-text">{{ order.phone }}</p>
                        <p class="card-text">{{ order.email }}</p>
                        <p class="card-text">{{ order.address_line }}</p>
                    </div>
                </div>

                <div class="card">
                    <h5 class="card-header">PayPal</h5>
                    <div class="card-body">
                        <p class="card-text"></p>
                    </div>
                </div>

                <div class="card">
                    <h5 class="card-header">Review Products</h5>
                    <div class="card-body">
                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="120">Quantity</th>
                                    <th scope="col" width="120">Price</th>
                                </tr>
                            </thead>

                            <tbody>

                                {% for cart_item in cart_items %}
                                    <tr>
                                        <td>
                                            <figure class="itemside align-items-center">
                                                <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                                                    <p class="text-muted small">
                                                        {% if cart_item.variations.all %}
                                                            {% for item in cart_item.variations.all %}
                                                                {{ item.variation_category | capfirst }} : {{ item.variation_value  | capfirst }}
                                                                <br>
                                                            {% endfor %}
                                                        {% endif %} 
                                                    </p>
                                                </figcaption>
                                            </figure>
                                        </td>

                                        <td> 
                                            <label for="">{{ cart_item.quantity }}</label>
                                        </td>

                                        <td> 
                                            <div class="price-wrap"> 
                                                <var class="price">${{ cart_item.sub_total }}</var> 
                                                <small class="text-muted">${{ cart_item.product.price }} each </small> 
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </aside> 

            <aside class="col-lg-4">
        
                <div class="card">
                <div class="card-body">
                    <dl class="dlist-align">
                    <dt>Total price:</dt>
                    <dd class="text-right">${{ total }}</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt>Tax:</dt>
                    <dd class="text-right">${{ tax }}</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt>Total:</dt>
                    <dd class="text-right text-dark b"><strong>${{ total_with_tax }}</strong></dd>
                    </dl>
                    <hr>
                    <p class="text-center mb-3">
                        <img src="{% static 'images/misc/payments.png' %}" height="27">
                    </p>

                    <div id="paypal-button-container">
                        <!-- PayPal button loads here -->
                    </div>

                </div>
                </div> 
        
            </aside> 
        
        </div> 
        
        </div> 
    </section>

    <!-- PayPal Script -->
<script>

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // 
                if (cookie.substring(0, name.lenght + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var amount = "{{ total_with_tax }}";
    var url = "{% url 'orders:payments' %}";
    var csrftoken = getCookie('csrftoken');
    var orderID = "{{ order.order_number }}";
    var payment_method = 'PayPal'
    var redirect_url = "{% url 'orders:order_complete' %}"

    // Render PayPal button into #paypal-button-container
    paypal.Buttons({

        // Order is created on the server and the order id is returned
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: amount,
                    }
                }]
            });
        },

        // Finalize the transaction on the server after payer approval
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                // Show a success message to the buyer
                console.log(details);
                sendData()
                function sendData(){
                    fetch(url, {
                        method: 'POST',
                        headers: {
                            "Content-type": "application/json",
                            "X-CSRFToken": csrftoken,
                        },
                        body: JSON.stringify({
                            orderID: orderID,
                            transID: details.id,
                            payment_method: payment_method,
                            status: details.status,
                        }),
                    })
                    .then((response) => response.json())
                    .then((data) => {
                        window.location.href = redirect_url + '?order_number='+data.order_number+'&payment_id'+data.transID;
                    });
                }
            });
        }
    }).render('#paypal-button-container');
    </script>
{% endblock %}